tracing {
  enabled = false
  service-name = "jigasi"
  # Required when enabled:
  # otlp-endpoint = "http://localhost:4317"
  # otlp-protocol = "grpc" # "grpc" or "http"
}

org.jitsi.jigasi {
  rest {
    host = "127.0.0.1"
    port = 8788
    tls-port = 8743
  }
  transcription {
    port = 0
    tls-port = 0
  }
}
