#!/bin/bash
# postinst script for jigasi
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    configure)

        CONFIG="/etc/jitsi/jigasi/config"

        OLDCONFIG="false"
        # migrate any old config found
        if [ -f "/etc/default/jigasi" ]; then
            mv /etc/default/jigasi $CONFIG
        fi
        # we don't want to regenerate config on upgrade
        if [ -f $CONFIG ]; then
            . $CONFIG
            if [ -n "$JIGASI_SIPUSER" ] && [ -n "$JIGASI_SIPPWD" ] && [ -n "$JIGASI_SECRET" ]; then
                OLDCONFIG="true"
            fi
        fi

        JICOFO_JAVA_SYS_PROPS_EXIST="true"
        # let's check whether there is a setting in the $CONFIG
        # for home folder and logging props file
        if [ ! -n "$JAVA_SYS_PROPS" ]; then
            JICOFO_JAVA_SYS_PROPS_EXIST="false"
        fi

        # use any old config found
        if [ -f "/etc/default/jitsi-videobridge" ]; then
            . /etc/default/jitsi-videobridge
        else
            # we need JVB vars for the hostname
            . /etc/jitsi/videobridge/config
        fi

        # generate config on new install
        if [ "$OLDCONFIG" = "false" ]; then

            # debconf SIP account questions
            . /usr/share/debconf/confmodule
            db_get jigasi/sip-account
            JIGASI_SIPUSER="$RET"
            db_get jigasi/sip-password
            JIGASI_SIPPWD=$(echo -n $RET | base64 -)
            db_stop

            # 8-chars random secret, alternative to pwgen 8
            JIGASI_SECRET=`head -c 8 /dev/urandom | tr '\0-\377' 'a-zA-Z0-9a-zA-Z0-9a-zA-Z0-9a-zA-Z0-9@@@@####'`

            # storing default for later use by Jigasi and other packages
            echo '# Jigasi settings' > $CONFIG
            echo "JIGASI_SIPUSER=$JIGASI_SIPUSER" >> $CONFIG
            echo "JIGASI_SIPPWD=$JIGASI_SIPPWD" >> $CONFIG
            echo "JIGASI_SECRET=$JIGASI_SECRET" >> $CONFIG
            echo "JIGASI_OPTS=\"\"" >> $CONFIG
        fi

        # let's check whether there is a setting in the $CONFIG
        # logging props file, if missing add it
        if [ "$JICOFO_JAVA_SYS_PROPS_EXIST" = "false" ]; then
            echo >> $CONFIG
            echo '# adds java system props that are passed to jigasi (default are for logging config file)' >> $CONFIG
            echo "JAVA_SYS_PROPS=\"-Djava.util.logging.config.file=/etc/jitsi/jigasi/logging.properties\"" >> $CONFIG
        fi

        # we don't want to start the daemon as root
        if ! getent group jitsi > /dev/null ; then
            groupadd jitsi
        fi
        if ! getent passwd jigasi > /dev/null ; then
            useradd -r -g jitsi --shell /bin/bash --create-home -d /usr/share/jigasi jigasi
        fi
        if ! groups jigasi | grep '\bjitsi\b' > /dev/null ; then
            usermod -g jitsi jigasi
        fi

        # we create home folder only if it doesn't exist
        if [ ! -d /usr/share/jigasi ]; then
            mkdir -p /usr/share/jigasi
        fi


        # we claim the home folder of jigasi in case it is owned by someone else
        OWNER=$(stat -c '%U' /etc/jitsi/jigasi)
        GROUP=$(stat -c '%G' /etc/jitsi/jigasi)
        if ! dpkg-statoverride --list /etc/jitsi/jigasi/* >/dev/null && [ "$OWNER:$GROUP" != "jigasi:jitsi" ]; then
            chown -R jigasi:jitsi /etc/jitsi/jigasi
            chown -R jigasi:jitsi /usr/share/jigasi
            OWNER=jigasi
            GROUP=jitsi
        fi

        CONFIG_DIR=$(dirname $CONFIG)
        if ! dpkg-statoverride --list "$CONFIG_DIR" >/dev/null; then
                chown root:$GROUP "$CONFIG_DIR"
                chmod 750 "$CONFIG_DIR"
        fi

        if ls /var/log/jitsi/jigasi* 1>/dev/null 2>&1 ;then
            chown -f -R $OWNER:$GROUP /var/log/jitsi/jigasi*
            chmod -f -R 640 /var/log/jitsi/jigasi*
            if [ -d /var/log/jitsi/jigasi ]; then
                find /var/log/jitsi/jigasi -type d -exec chmod 750 '{}' \;
            fi
        fi

        # populate the config with debconf values
        sed -i "s/<<JIGASI_SIPUSER>>/$JIGASI_SIPUSER/g" /etc/jitsi/jigasi/sip-communicator.properties
        sed -i "s/<<JIGASI_SIPPWD>>/$JIGASI_SIPPWD/g" /etc/jitsi/jigasi/sip-communicator.properties
        SIPSERVER=`echo $JIGASI_SIPUSER | cut -d'@' -f 2`
        sed -i "s/<<JIGASI_SIPSERVER>>/$SIPSERVER/g" /etc/jitsi/jigasi/sip-communicator.properties

        PROSODY_HOST_CONFIG="/etc/prosody/conf.avail/$JVB_HOSTNAME.cfg.lua"
        JIGASI_PROSODY="Component \"callcontrol.$JVB_HOSTNAME\" component_secret = \"$JIGASI_SECRET\""
        # update prosody config
        if [ ! "$(grep "Component \"callcontrol.$JVB_HOSTNAME\"" /etc/prosody/prosody.cfg.lua)" ] || [ ! "$(grep "Component \"callcontrol.$JVB_HOSTNAME\"" $PROSODY_HOST_CONFIG)" ]; then
            echo $JIGASI_PROSODY >> $PROSODY_HOST_CONFIG
        else
            sed "/Component \"callcontrol.$JVB_HOSTNAME\"/d" -i $PROSODY_HOST_CONFIG
            echo $JIGASI_PROSODY >> $PROSODY_HOST_CONFIG
        fi
        invoke-rc.d prosody restart

        # update jitsi-meet config
        JITSI_MEET_CONFIG="/etc/jitsi/meet/$JVB_HOSTNAME-config.js"
        if [ ! "$(grep "call_control: 'callcontrol.$JVB_HOSTNAME'" $JITSI_MEET_CONFIG)" ] || [ "$(grep "//call_control: 'callcontrol.$JVB_HOSTNAME'" $JITSI_MEET_CONFIG)" ]; then
            JIGASI_MEET="        call_control: 'callcontrol.$JVB_HOSTNAME'"
            #sed -i "s/hosts:\ {/hosts:\ {\n\t$JIGASI_MEET/g" /usr/share/jitsi-meet/config.js
            sed -i "s/.*call_control: .*/$JIGASI_MEET/" $JITSI_MEET_CONFIG
        fi

        # ensure jigasi is not running - it will be started at the end
        if [ "$(ps -C jigasi.sh --no-headers -o pid)" ]; then
            invoke-rc.d jigasi stop || true
        fi
        if [ -x "/etc/init.d/jigasi" ]; then
            update-rc.d jigasi defaults >/dev/null
        fi

        # clean up old jigasi group
        if getent group jigasi > /dev/null; then
            groupdel jigasi
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
